[workspace]
resolver = "2"

members = [
    "radius",
    "examples/ais3",
    "examples/r100",
    "examples/r200",
    "examples/unbreakable",
    "examples/dex",
    "examples/babyre",
    "examples/frida",
    "examples/tracer",
    "examples/ollvm",
    "examples/statically-linked"
]

[profile.release]
lto = true
opt-level=3
