[package]
name = "statically-linked"
version = "0.1.0"
authors = ["Lennard Hofmann <lennard.hofmann@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
radius2 = { path = "../../radius" }
